# The URL the site will be built for
base_url = "https://example.com"

# The site title and description; used in feeds by default.
title = "Strix"
description = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", feed = true, paginate_by = 10 },
    { name = "categories", feed = true, paginate_by = 10 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

highlight_theme = "OneHalfDark"

[extra]
# ============================================
# Basic Information
# ============================================
author = "Great Grey Owl"
author_img = "/images/owl_profile.png"
subtitle = "A powerful, lightweight theme for Zola built with Tailwind CSS."
bio = "Strix Nebulosa @ Dense Coniferous"
# "Wait, listen, and watch for prey, then swoop down"

# ============================================
# Navigation Bar
# ============================================
logo = "/images/strix_logo2.png"
show_logo = true

# Menu
# Format: [{ name = "Display Name", url = "Link Path" }]
# Menu with optional submenu
menu = [
  { name = "Home", url = "/" },
  { name = "Posts", url = "/posts", submenu = [
      { name = "All Posts", url = "/posts" },
      { name = "Tech", url = "/posts/tech" },
      { name = "Tutorial", url = "/posts/tutorial" }
    ]},
  { name = "About", url = "/about" },
]

# Toggle switch: Whether to display Tags and Categories links in the footer
show_categories = true
show_tags = true

# ============================================
# Social Links 
# ============================================
# name: github, email
socials = [
  { name = "github", url = "https://github.com/your-username" },
  { name = "email", url = "mailto:your-email@gmail.com" },
]

# ============================================
# Homepage Sections
# ============================================
# Available modules: profile, recent_posts, experience, education, featured_projects
# The order determines the display sequence. You can rearrange or remove modules as needed.
homepage = [
  "profile",
  "recent_posts",
  "experience",
  "education",
  "featured_projects"
]
